### ISSUE TITLE
Hammered by webhook requests

### ISSUE THREAD

**Issue by MegaphoneJon** [aghstrategies/com.aghstrategies.airmail#56] opened 2024-10-28 17:30 UTC
I have a client who just sent out an email, and right now there server seems to be getting several requests to the Airmail endpoint from the SendGrid API, and the server load has spiked to the point of non-responsiveness.

Have you seen this?  I killed the cron job to stop more mailings from going out, and now a few minuts later the airmail webhooks have died down to a regular amount.

I'm wondering if SendGrid has increased the rate at which they fire webhooks, or a recent change to Airmail might be slowing down the processing - I upgraded to 2.2.4 last night, but I don't see anything in there that looks problematic.

**Comment by MegaphoneJon** [comment] 2024-10-28 17:42
Related - the SendGrid-specific Airmail documentations recommends enabling these webhooks: Opened, Clicked, Mark as Span, Unsubscribed From, Dropped, Bounced.

Does Airmail make use of "Opened" and "Clicked"? I would assume that it uses its own open and click-through tracking.  It would greatly reduce the number of POST requests made to the server during a mailing.

**Comment by kcristiano** [comment] 2024-12-05 23:27
@MegaphoneJon did you solve this issue.  I am seeing on one of our sites and wonder if we do need 'opened' and 'clicked' events enabled.

**Comment by MegaphoneJon** [comment] 2024-12-06 03:54
@kcristiano I did not.  I'm fairly convinced now that CiviMail template rendering, or open/click-through processing, has take a big performance hit in the last couple of versions.  This aggravates the issue but isn't the main culprit, so I've lowered the priority.  But if @alifrumin or @agh1 can comment on the use of "Opened" and "Clicked" in Airmail, I could write a quick fix.

**Comment by alifrumin** [comment] 2024-12-06 14:54
We do respond to Open and Clicked - https://github.com/aghstrategies/com.aghstrategies.airmail/blob/master/CRM/Airmail/EventAction.php -- but those are both less and less useful these days https://civicrm.org/blog/artfulrobot/how-interpret-mailing-statistics-click-and-open-rates, we are open to stopping tracking that if you guys thing it would be helpful.

**Comment by kurund** [comment] 2024-12-18 17:48
@alifrumin 

As CiviCRM also tracks open, will this lead to double counting?

**Comment by kurund** [comment] 2024-12-18 18:08
> @alifrumin
> 
> As CiviCRM also tracks open, will this lead to double counting?

Just confirmed in case on opens it records it twice at least for SendGrid

**Comment by alifrumin** [comment] 2024-12-20 16:11
Originally I wrote some of this code but its been awhile since I focused on it. I am documenting my understanding below of how things are currently working to be sure I am understanding this issue correctly so we can put together a path forward.

As I understand it the first step for SendGrid/ Airmail integration is to configure a webhook. To do this an administrator logs into sendgrid and selects the "Actions to be posted to the webhook" see screenshot below:

![Screenshot from 2024-12-20 10-58-34](https://github.com/user-attachments/assets/2c56827a-70a4-4657-9c94-053ccdd2f426)

The current [airmail documentation](https://github.com/aghstrategies/com.aghstrategies.airmail/blob/master/docs/Sendgrid.md) recommends selecting "Opened" as @MegaphoneJon mentioned.

CiviCRM also has the ability to track opens and defaults to doing so here: https://dmaster.demo.civicrm.org/civicrm/admin/setting/preferences/mailing?reset=1:

![Screenshot from 2024-12-20 11-07-36](https://github.com/user-attachments/assets/07448263-7414-4eb3-988d-a4ee4d451888)
 
As I understand it when the SendGrid webhook is configured to post the "Opened" action and CiviCRM is configured to " Enable open tracking by default" Opens are being tracked twice.

Is that correct?

If so theoretically one could resolve this by updating the documentation for configuring the webhook to be more specific regarding playing nicely with CiviCRM open tracking.

**Comment by kcristiano** [comment] 2024-12-20 16:55
@alifrumin I think the only reason to track SendGrid opens and clicks is if you allow set sendgrid tracking up at https://app.sendgrid.com/settings/tracking  

If there tracking is enabled, the URL changes from a CiviCRM URL to sendgrid and CiviCRM may not get the notices.  

If sendgrid is not doing the tracking I think not turning on open/click on the webhook makes sense.

When it has happened to our clients we've gotten thousands of webhooks sent just after a mailing is sent.   I don't have any pattern on data on why, but I do suspect it's email services or clients downloading the images.  

My current thinking is to handle via documentation:   Turn off SendGrid tracking and do not have webhooks send open/click events and ensure that CiviCRM is set to track these.

what do you think?

**Comment by alifrumin** [comment] 2024-12-20 17:00
@kcristiano that makes sense to me. I will make a pr with those documentation changes

**Comment by alifrumin** [comment] 2024-12-20 17:19
@kcristiano if this looks good to you I feel good about merging it.

**Comment by alifrumin** [comment] 2024-12-20 21:45
closing now that documentation changes have been merged

**Closed by alifrumin** 2024-12-20 21:45 UTC
